---
abstract: 'Collections framework for  B<CRUD> of the data or objects.'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collection
provides:
  Collection:
    file: lib/Collection.pm
    version: 0.47
  Collection::AutoSQL:
    file: lib/Collection/AutoSQL.pm
    version: 1.1
  Collection::AutoSQLnotUnique:
    file: lib/Collection/AutoSQLnotUnique.pm
    version: 0.01
  Collection::Mem:
    file: lib/Collection/Mem.pm
    version: 0.01
  Collection::Memcached:
    file: lib/Collection/Memcached.pm
    version: 0.01
  Collection::Storable:
    file: lib/Collection/Storable.pm
    version: 0.01
  Collection::Utl::ActiveRecord:
    file: lib/Collection/Utl/ActiveRecord.pm
    version: 0.01
  Collection::Utl::Base:
    file: lib/Collection/Utl/Base.pm
    version: 0.01
  Collection::Utl::HashUnion:
    file: lib/Collection/Utl/HashUnion.pm
    version: 0.01
  Collection::Utl::Item:
    file: lib/Collection/Utl/Item.pm
    version: 0.02
  Collection::Utl::LazyObject:
    file: lib/Collection/Utl/LazyObject.pm
    version: 0.01
  Collection::Utl::Mirror:
    file: lib/Collection/Utl/Mirror.pm
    version: 0.02
requires:
  Storable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.47
