---
abstract: 'CRUD framework'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collection
provides:
  Collection:
    file: lib/Collection.pm
    version: 0.57
  Collection::AutoSQL:
    file: lib/Collection/AutoSQL.pm
    version: 1.1
  Collection::AutoSQLnotUnique:
    file: lib/Collection/AutoSQLnotUnique.pm
    version: 0.01
  Collection::CrcColl:
    file: lib/Collection/CrcColl.pm
    version: 0.11
  Collection::Index:
    file: lib/Collection/Index.pm
    version: 0
  Collection::Mem:
    file: lib/Collection/Mem.pm
    version: 0.01
  Collection::Memcached:
    file: lib/Collection/Memcached.pm
    version: 0.01
  Collection::Storable:
    file: lib/Collection/Storable.pm
    version: 0.01
  Collection::Utl::ActiveRecord:
    file: lib/Collection/Utl/ActiveRecord.pm
    version: 0.01
  Collection::Utl::Base:
    file: lib/Collection/Utl/Base.pm
    version: 0.01
  Collection::Utl::Flow:
    file: lib/Collection/Utl/Flow.pm
    version: 0.01
  Collection::Utl::HashUnion:
    file: lib/Collection/Utl/HashUnion.pm
    version: 0.01
  Collection::Utl::Item:
    file: lib/Collection/Utl/Item.pm
    version: 0.02
  Collection::Utl::LazyObject:
    file: lib/Collection/Utl/LazyObject.pm
    version: 0.01
  Collection::Utl::Mirror:
    file: lib/Collection/Utl/Mirror.pm
    version: 0.02
  Collection::Utl::StoreDir:
    file: lib/Collection/Utl/StoreDir.pm
    version: 0
requires:
  Flow: 0.6
  JSON::XS: 2.29
  Storable: 0
  String::CRC32: 1.4
resources:
  license: http://dev.perl.org/licenses/
version: 0.57
